# Generated by Django 4.2 on 2023-04-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voter_ip',
        ),
    ]
