# Generated by Django 4.2 on 2023-04-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_vote_voter_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_author',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
