# Generated by Django 4.2 on 2023-04-22 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='OneChoice',
        ),
    ]
