# Generated by Django 4.2 on 2023-04-22 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0002_rename_vote_onechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[('one', 'one'), ('multi', 'multi')], max_length=15),
        ),
        migrations.CreateModel(
            name='MultiChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('choices', models.ManyToManyField(to='model.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.question')),
                ('vote_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
