# Generated by Django 4.2 on 2023-04-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_question_choice_type_multichoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multichoice',
            old_name='choices',
            new_name='choice',
        ),
    ]
