# Generated by Django 4.2 on 2023-04-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_rename_choices_multichoice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator_type',
            field=models.CharField(choices=[('one', 'one'), ('multi', 'multi')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
