# Generated by Django 4.2 on 2023-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_question_creator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creator_type',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client')], max_length=100),
        ),
    ]
